-- MySQL Script generated by MySQL Workbench
-- Sat Feb 15 00:06:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema InstagramDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema InstagramDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `InstagramDb` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `InstagramDb` ;

-- -----------------------------------------------------
-- Table `InstagramDb`.`Accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InstagramDb`.`Accounts` ;

CREATE TABLE IF NOT EXISTS `InstagramDb`.`Accounts` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `InstagramDb`.`Followers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InstagramDb`.`Followers` ;

CREATE TABLE IF NOT EXISTS `InstagramDb`.`Followers` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(255) NOT NULL,
  `HashTagId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `InstagramDb`.`Follows`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InstagramDb`.`Follows` ;

CREATE TABLE IF NOT EXISTS `InstagramDb`.`Follows` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `AccountId` INT(11) NOT NULL,
  `FollowerId` INT(11) NOT NULL,
  `Status` TINYINT(1) NULL DEFAULT '1',
  `FollowDate` DATE NULL DEFAULT NULL,
  `UnFollowDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `InstagramDb`.`HashTags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InstagramDb`.`HashTags` ;

CREATE TABLE IF NOT EXISTS `InstagramDb`.`HashTags` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `ChuDe` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
